# questionnaires.py

DISCOVERY = [
    {"id": "agents", "label": "Approx. number of agents", "type": "select",
     "options": ["<20", "20–100", "100–300", "300+"]},
    {"id": "structure", "label": "How are teams structured?", "type": "select",
     "options": ["Single central centre", "Multiple departmental teams", "Mixed", "Not sure"]},
    {"id": "channels_now", "label": "Channels in use (select all)", "type": "multiselect",
     "options": ["Voice", "Webchat", "Email", "SMS", "Social", "Self-service portal", "In-person"]},
    {"id": "channel_pain", "label": "Which channel causes most pain?", "type": "select",
     "options": ["Voice", "Email", "Webchat", "Social", "Not sure"]},
    {"id": "top_services", "label": "Top interaction drivers (free text)", "type": "text"},
    {"id": "telephony", "label": "Telephony estate", "type": "select",
     "options": ["Avaya", "Cisco", "Mitel", "Teams Voice", "8x8", "RingCentral", "Other/Unknown"]},
    {"id": "crm", "label": "CRM/case management", "type": "select",
     "options": ["Dynamics 365", "Salesforce", "Netcall Liberty", "Civica", "Capita ONE", "ServiceNow", "None/Unknown"]},
    {"id": "self_service", "label": "Self-service/portal adoption", "type": "select",
     "options": ["None/basic", "Some services", "Widely used", "Not sure"]},
    {"id": "pain_points", "label": "Biggest operational pain (select up to 3)", "type": "multiselect",
     "options": ["Long queues", "Multi-channel demand mgmt", "Poor integration", "Limited automation",
                 "Inconsistent CX", "Aging PBX", "Weak MI/analytics"]},
    {"id": "priorities", "label": "Top 2–3 priorities", "type": "multiselect",
     "options": ["Cost savings", "Improve CX", "Channel expansion", "Upgrade telephony", "Integration/workflow",
                 "Resilience/BCP"]},
    {"id": "it_capacity", "label": "Internal IT/dev capacity", "type": "select",
     "options": ["Low", "Medium", "High", "Not sure"]},
    {"id": "budget", "label": "Budget band (run + change)", "type": "select",
     "options": ["Low", "Medium", "High", "Unknown"]},
    {"id": "urgency", "label": "Target go-live timescale", "type": "select",
     "options": ["<3 months", "3–6 months", "6–12 months", "12+ months"]},
    {"id": "security", "label": "Security/sovereignty driver", "type": "select",
     "options": ["Yes", "No", "Not sure"]},
    {"id": "uk_support", "label": "Require UK-based support?", "type": "select",
     "options": ["Yes", "No", "Not sure"]},
]

DIAGNOSTIC = [
    {"id": "strategy", "label": "Top strategic drivers (pick up to 3)", "type": "multiselect",
     "options": ["Cost savings", "Channel shift", "CX improvement", "WEM/workforce",
                 "Resilience/BCP", "Data/insight", "Automation/AI"]},
    {"id": "automation", "label": "Automation ambition (3-yr)", "type": "select",
     "options": ["Switchboard", "Service requests", "Transactions", "Complex/agentic"]},
    {"id": "omni", "label": "Channel strategy", "type": "select",
     "options": ["Voice-first + digital", "Digital-first", "True omni-channel orchestration"]},
    {"id": "hand_off", "label": "Seamless channel hand-off required?", "type": "select",
     "options": ["Yes", "No", "Not sure"]},
    {"id": "integration", "label": "Integration maturity", "type": "select",
     "options": ["Manual/siloed", "Point-to-point", "Middleware/APIs", "Mature integration platform"]},
    {"id": "back_office", "label": "Priority back-office systems (free text)", "type": "text"},
    {"id": "procurement", "label": "Commercial model preference", "type": "select",
     "options": ["Subscription (per agent/month)", "Consumption (pay per use)", "CapEx", "No preference"]},
    {"id": "delivery", "label": "Delivery capacity preference", "type": "select",
     "options": ["Turnkey vendor", "Hybrid (partner + in-house)", "Open platform we control"]},
    {"id": "lock_in", "label": "Avoid vendor lock-in?", "type": "select",
     "options": ["Not a concern", "Important", "Critical"]},
    {"id": "ms_bias", "label": "Microsoft stack bias (Teams/D365)?", "type": "select",
     "options": ["Yes", "No", "Mixed/Unsure"]},
]
